[package]
name    = "pouf"
version = "0.1.0"
authors = ["Ferry Jérémie <ferryjeremie@free.fr>"]

[dependencies]
clap = "2.33"
# fake = { path = "../fake-rs/fake", features=['chrono', 'http', 'semver'] }
fake = { version="2.4", features=['chrono', 'http'] }
chrono = { version = "0.4" }
http = { version = "0.2" }
semver = { version = "0.11" }
