[package]
name = "pouf"
version = "0.1.0"
authors = ["Ferry Jérémie <ferryjeremie@free.fr>"]
description = "Pouf is a cli program for produce fake datas."
keywords = ["app", "cli", "faker", "data", "random"]
categories = ["command-line-utilities"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/mothsart/pouf"
homepage = "https://github.com/mothsart/pouf"
edition = "2018"
build = "build.rs"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap.git", rev = "73cf47a", package = "clap" }
fake = { version="2.4", features=['chrono', 'http'] }

chrono = { version = "0.4" }
http = { version = "0.2" }
semver = { version = "0.11" }

[build-dependencies]
clap = { git = "https://github.com/clap-rs/clap.git", rev = "73cf47a", package = "clap" }
clap_generate = { git = "https://github.com/clap-rs/clap.git", rev = "73cf47a", package = "clap_generate" }
